#+title: typst-preview.el
#+author: Håvard Damm-Johnsen
Live preview of typst files inside emacs! Building on [[https://github.com/Enter-tainer/typst-preview][typst-preview]], which was originally written for VS Code, and also inspired by [[https://github.com/chomosuke/typst-preview.nvim][typst-preview.nvim]].

*Features*:
- Live preview of edits
- Source to preview jumping
- Preview to source jumping

* Installation

** MELPA
Currently not on Melpa

** Manual installation

Install the typst-preview binary from
https://github.com/Enter-tainer/typst-preview/releases
and make sure it's in your $PATH. To test this, create test.typ and run
#+begin_src bash
typst-preview test.typ
#+end_src
 
Then put ~typst-preview.el~ in your load-path, and put this in your init file:
#+begin_src emacs-lisp
 (require 'typst-preview)
#+end_src

Or, if you use ~use-package~, try:

#+begin_src emacs-lisp
(use-package websocket)
(use-package typst-preview
  :straight nil 			; if you use straight
  :load-path "path-to-typst-preview.el")
#+end_src

* Usage & configuration

** Basic usage
Inside a .typ-file, run ~M-x typst-preview-mode~. This will start a preview in your default browser, and connect the source buffer to the server, sending live updates.

Start, stop and restart ~typst-preview~ using ~M-x typst-preview-start~, ~M-x typst-preview-stop~ and ~M-x typst-preview-restart~. 

** Change default browser

To preview the .typ file in a non-default browser: 
#+begin_src emacs-lisp
(setq typst-preview-browser "safari")
#+end_src

To preview the .typ file using ~xwidget~, provided your emacs is built with ~xwidget~-support: 

#+begin_src emacs-lisp
(setq typst-preview-browser "xwidget")
#+end_src

** Details:
Enabling ~typst-preview-mode~ runs ~typst-preview-start~, which does a few things:
- Starts ~typst-preview~ on the current file, sending results to the buffer ~*ws-typst-server*~.
- Connects to the ~typst-preview~ server using ~websocket~
- Opens a browser pointing at the address of the preview
- Adds a hook to ~after-change-functions~ which sends the buffer to the server at each keystroke. 

* Todos: 
- [ ] Open browsers in linux/windows, not just MacOS
- [ ] Ensure that opening several .typ instances works
- [ ] Clean up typst-preview-start and fix the xwidget hack



